### PR TITLE
Facebook branch

### PR DESCRIPTION
**Pull request by apricot12**
Added associations to facilitate friendships between users.

### CODE REVIEW

**Comment by arikarim** [comment]
Hello hope you are doing well

we made the ERD and it's inside that (Docs) folder at the root of the project.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED 🔴 🛑 
--------
Hello, @apricot12 @arikarim you are doing a great job. Your ERD is clear and well structured 👍 👏 
However, there is on changes to make 🛠️ see below 👀 👇 
--------
- [ ] User table has image_link column. Currently, you don't have this column. Please add it. 

imglink
-----------
Make the required change and send it again for another review.
Reachme on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodriguez 
HAPPY CODING!!

cat

**Comment by arikarim** [comment]
Thanks for the review.
we added the image link column.

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Requires changes :yellow_circle:      
### Hello team :wave: 

Thanks for working on the required changes but make sure you include image_link under users entity as it is an attribute the describes a given user. (currently image_link is included under friendships table)

#### Please work on the changes required and submit a new request once you are ready!

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Part-Time TSE)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @arikarim and @apricot12! Nice work implementing the changes that were requested by the previous TSE. This PR is now approved. Congratulations.

**Pull request merged**
